// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const SITE_TITLE = "Hi, I'm Casey!";
export const SITE_DESCRIPTION = `
I love to help people and groups become more happy and effective 🌈.
I like: singing, dancing, blowing bubbles, enthusiasm, clear communication.
`;
export const REDIRECTS = {
  "bashautocomplete": "https://gist.github.com/caseywatts/6c989ed8e942a75f97f5e05dcda003f1",
  "browsersync": "https://gist.github.com/caseywatts/8266527a24667aad80b7d6127130de06",
  "bubbleparty": "https://www.facebook.com/bubblepartydc/",
  "chromeextensionworkshop": "https://gist.github.com/caseywatts/8eec8ff974dee9f3b247",
  "culturesmithing-railsconf-2022": "https://docs.google.com/document/d/1OBIVaA43I1aQnPHmmCAWvpPmqG3_4DAVwZ-WRBcidzk/edit",
  "darken": "https://gist.github.com/caseywatts/251ca80557e3599332c218c8b5c60029",
  "dotfiles": "https://github.com/caseywatts/dotfiles",
  "eggs": "/soundboard#eggs",
  "electronworkshop": "https://gist.github.com/caseywatts/83783910d681989656962a434ef33c94",
  "elegant": "/soundboard#sardonyx-elegant",
  "feedback": "https://forms.gle/t1F3JQFJWdcg1Ucs5",
  "flipit": "https://gist.github.com/caseywatts/f9be22834ad05e43ea8d3a0717849deb",
  "github": "https://github.com/caseywatts",
  "graphviz": "https://gist.github.com/caseywatts/be69bf941fa1f8e264bd07de698366a0",
  "instagram": "https://www.instagram.com/heycaseywattsup/",
  "interactive-tools-2022": "https://happyandeffective.notion.site/ATD-Interactive-Tools-Event-d4a903def54340be81ac8e19d55956d5",
  "linkedin": "https://www.linkedin.com/in/heycaseywattsup",
  "markdown-here": "https://github.com/caseywatts/markdown-here-css",
  "mediawiki-on-heroku": "https://gist.github.com/caseywatts/d04bda6626ef2c6c8f97",
  "mindmanipulation": "https://docs.google.com/document/d/e/2PACX-1vTW1b3aErmPfUWmyj9_bARHW-Cl-7b6q7acmIdWOg5KhGhErYd5NDyZioXFqamTRMMdPlORCD4WOGu9/pub",
  "mindmanipulationvideo": "https://www.youtube.com/watch?v=AtefvXagutM",
  "minecraft": "https://gist.github.com/caseywatts/869d30998dc847efc428528a73a92a66",
  "pixlr": "https://gist.github.com/caseywatts/065efcb61465ddfbc2d6",
  "ptt": "https://gist.github.com/caseywatts/561bc498b6feec3d419b29a65d916663",
  "quicktime": "https://gist.github.com/caseywatts/1046ec6fd908d7d76f07e5ea8ef40b32",
  "quicktimegifs": "https://gist.github.com/caseywatts/5424604",
  "resume": "/resume.pdf",
  "selfpublish": "https://gist.github.com/caseywatts/3d8150fe04e0d8462cfc4d51b9856d39",
  "selpattern": "https://gist.github.com/caseywatts/46643c9c0825c5e8b1e2542b0a150659",
  "slackemoticons": "https://github.com/elight/slack_emoticon_inhaler",
  "slugify": "https://gist.github.com/caseywatts/1f6f8346a31f937246b4",
  "sogood": "/soundboard#teengirlsquad-sogood",
  "twitter": "http://twitter.com/heycaseywattsup",
  "mastodon": "https://social.coop/@heycaseywattsup",
  "whoopsies": "/soundboard#catbug-whoopsies",
  "gists-and-tricks": "/projects",
  "workshops": "https://happyandeffective.com/workshops",
  "coaching": "https://happyandeffective.com/coaching",
  "workshops/matrix-based-prioritization-for-strong-team-alignment": "https://happyandeffective.com/workshops",
  "workshops/feeling-understood": "https://happyandeffective.com/workshops",
  "workshops/team-health": "https://happyandeffective.com/workshops",
  "2012/12/07/code-swarm": "code-swarm",
  "2012/12/11/Using_Jekyll": "using-jekyll",
  "2012/12/12/markdown_to_slide_presentation": "markdown-to-slide-presentation",
  "2012/12/12/tagging_groups_in_gmail": "tagging-groups-in-gmail",
  "2012/12/16/screencasting": "screencasting",
  "2012/12/17/markdown_in_gmail": "markdown-in-gmail",
  "2012/12/18/google_drive_=_web_publishing": "google-drive-=-web-publishing",
  "2013/01/11/service_now_tips": "service-now-tips",
  "2013/06/16/upgrading_mediawiki": "upgrading-mediawiki",
  "2013/07/09/service_now_tips_revised": "service-now-tips-revised",
  "2013/07/23/yale_browser_searches": "yale-browser-searches",
  "2013/07/23/yale_chrome_extensions": "yale-chrome-extensions",
  "2013/11/19/buying_a_laptop_things_to_consider": "buying-a-laptop-things-to-consider",
  "2014/05/31/bus_gpssing": "bus-gpssing",
  "2014/10/03/knowledge_management": "knowledge-management",
  "2015/11/28/chrome-devtools-new-features": "chrome-devtools-new-features",
  "2016/03/28/tech-shop-bubble-lamp": "tech-shop-bubble-lamp",
  "2017/12/14/discussion-facilitation": "discussion-facilitation",
  "2017/12/18/types-of-hunger": "types-of-hunger",
  "2018/08/23/codemods": "codemods",
  "2018/11/25/debugging-your-brain-1": "debugging-your-brain-1",
  "2018/12/16/debugging-your-brain-2": "debugging-your-brain-2",
  "2019/12/28/debugging-your-brain-3": "debugging-your-brain-3",
  "2019/12/28/debugging-your-brain-4": "debugging-your-brain-4",
  "2020/03/19/debugging-your-brain-5": "debugging-your-brain-d",
}
export const REDIRECT_FROMS = Object.keys(REDIRECTS);

export const CASEY_FACTS = [
  "💔 I can play Bad Romance on 15+ instruments",
  "🌈 I own an instrument in every color.",
  "💜 I used to work for Heroku, as an engineering manager and frontend developer.",
  "🔨 I used to work at Yale, leading a team of 300 students who repaired laptops, PCs, media equipment, and did software development.",
  "🛫 When I was 16 I learned how to fly a plane. I even soloed!",
  "🚗 I didn't learn to drive until I was 23. I didn't need it in cities!",
  "🏛️ I used to work for the US Government, working on Asylum/Immigration as a Product Manager.",
  "🧑🏻‍🏫 I used to teach software development full-time, through the Yale Entrepreneurial Institute.",
  "🎨 I designed this whole website myself! Using Astro and Tailwind.",
  "🫡 I was in a pre-military program as a teen. They called me Major Watts (literally!)",
  "📘 I wrote a book! Debugging Your Brain bring together my backgrounds in psychology and software development."
]