export const EVENTS = [
  {
    emoji: "🦀",
    name: "Code for Baltimore",
    location: "online",
    description: "Use your technology skills to help local nonprofits and government groups become more effective.",
    participating: "hosting",
    category: "💻 tech",
    cost: "free",
    date: "2023-04-12",
    url:"https://www.meetup.com/code-for-baltimore/events/292410995/"
  },
  {
    emoji: "🎭",
    name: "2023 Baltimore Playwrights Festival: People Should Talk About What's Real",
    location: "Downtown Baltimore",
    description: "My partner Brian is in this! A play about infertility, miscarriage, abortion, and adoption.",
    participating: "attending",
    category: "🛝 fun",
    cost: "free",
    date: "2023-03-18",
    url: "https://www.eventbrite.com/e/2023-baltimore-playwrights-festival-people-should-talk-about-whats-real-tickets-576232375547"
  },
  {
    emoji: "🤣",
    name: "Improv Night (Highwire Improv)",
    location: "Downtown Baltimore",
    description: "an improvised comedy show",
    participating: "performing",
    category: "🛝 fun",
    cost: "free",
    date: "2023-03-11",
    url: "https://www.eventbrite.com/e/improv-comedy-night-at-charm-city-meadworks-tickets-532682978127?aff=eand"
  },
  {
    emoji: "☕️",
    name: "Baltimore Code and Coffee",
    location: "Baltimore (Hampden)",
    description: "a social event for tech people",
    participating: "hosting",
    category: "💻 tech",
    cost: "free",
    date: "2023-03-11",
    url: "https://www.meetup.com/baltimore-code-and-coffee/events/291982633/"
  },
  {
    name: "DC Product & Pastries + EdTech DMV",
    emoji: "🥐",
    location: "downtown DC",
    description: "a social event / discussion for Product Designers + Product Managers",
    participating: "hosting",
    category: "💻 tech",
    cost: "free",
    date: "2023-03-30",
    url: "https://www.meetup.com/product-and-pastries/events/292041025/"
  },
  {
    emoji: "🦀",
    name: "Code for Baltimore",
    location: "North of Baltimore",
    description: "Use your technology skills to help local nonprofits and government groups become more effective.",
    participating: "hosting",
    category: "💻 tech",
    cost: "free",
    date: "2023-03-02",
    url: "https://www.meetup.com/code-for-baltimore/events/291774037/"
  },
  {
    emoji: "🎶",
    name: "Baltimore Musical Improv Meetup",
    location: "Downtown Baltimore",
    description: "free interactive workshop - learn musical improv. no music or improv background required.",
    participating: "hosting",
    category: "🛝 fun",
    cost: "free",
    date: "2023-04-05",
    url: "https://www.meetup.com/baltimoremusicalimprov/events/291983711/"
  },
  {
    name: "Frontrunners Tech Conference",
    emoji: "🌎",
    location: "Arlington, VA",
    description: "a tech conference focused on javascript and frontend development. I'll be the emcee!",
    participating: "hosting",
    category: "💻 tech",
    cost: "$200",
    date: "2023-03-10",
    url: "https://frontrunners.tech/"
  },
  {
    name: "DC Product & Pastries",
    emoji: "🥐",
    location: "downtown DC",
    description: "a social event / discussion for Product Designers + Product Managers",
    participating: "hosting",
    category: "💻 tech",
    cost: "free",
    date: "2023-02-21",
    url: "https://www.meetup.com/product-and-pastries/events/291038771/"
  },
  {
    name: "Alexa's Birthday Comedy Show",
    emoji: "🤣",
    location: "Baltimore (Hampden)",
    description: "My friend Alexa is celebrating her birthday with standup/improv. My partner Brian is performing with her, too!",
    participating: "attending",
    category: "🛝 fun",
    cost: "$10",
    date: "2023-02-23"
  },
  {
    emoji: "☕️",
    name: "Baltimore Code and Coffee",
    location: "Baltimore (Hampden)",
    description: "a social event for tech people",
    participating: "hosting",
    category: "💻 tech",
    cost: "free",
    date: "2023-02-25",
    url: "https://www.meetup.com/baltimore-code-and-coffee/events/291624405/"
  },
  {
    emoji: "🎶",
    name: "Baltimore Musical Improv Meetup",
    location: "Downtown Baltimore",
    description: "free interactive workshop - learn musical improv. no music or improv background required.",
    participating: "hosting",
    category: "🛝 fun",
    cost: "free",
    date: "2023-03-01",
    url: "https://www.meetup.com/baltimoremusicalimprov/events/pmcbctyfcfbcb/"
  },
  {
    emoji: "👬",
    name: "Cultivating a Community-led Community Workshop",
    location: "online",
    description: "Casey will be teaching this 2-hour paid interactive workshop, for anyone interested in sustainable community building",
    participating: "hosting",
    category: "🤓 training",
    cost: "$86",
    date: "2023-03-13",
    url: "https://lu.ma/community-led-community-feb-2023"
  },
  {
    emoji: "🎲",
    name: "Unpub",
    location: "North of Baltimore",
    description: "indie board game conference, free for players",
    participating: "attending",
    category: "🛝 fun",
    cost: "free",
    date: "2023-03-15",
    endDate: "2023-03-20",
    url: "https://unpub.net/unpub-2023"
  },
  {
    emoji: "🎨",
    name: "MICA Grassroots Designfest",
    location: "downtown Baltimore",
    description: "a hack-day for designers to do social good projects",
    participating: "attending",
    category: "💻 tech",
    cost: "free",
    date: "2023-03-25",
    url: "https://designfest.weebly.com/"
  },
  {
    emoji: "🥇",
    name: "Casey's First Improv Show",
    location: "downtown DC",
    description: "the capstone performance for the Intro to Improv course Casey is taking",
    participating: "performing",
    category: "🛝 fun",
    cost: "free",
    date: "2023-04-01",
    url: "https://lu.ma/casey-first-improv-show"
  },
]